# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPlaneFit
                                 A QGIS plugin
 Fit planes using DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-30
        copyright            : (C) 2022 by Ondrej Lexa
        email                : lexa.ondrej@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoPlaneFit class from file GeoPlaneFit.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoplanefit import GeoPlaneFit
    return GeoPlaneFit(iface)
